const mongoose = require("mongoose");

const MAX_MESSAGE_LENGTH = 2000;

/**
 * A single chat message.
 *
 * The database is the source of truth for history - Socket.IO is only the
 * realtime transport, so every message is persisted before it is broadcast.
 *
 * `receiverId` mirrors the other participant of the direct conversation and
 * makes the "unread for me" query a single indexed lookup.
 *
 * `clientMessageId` is an optional idempotency key generated by the client so
 * a double clicked send button or a socket retry cannot write the same message
 * twice (enforced by a partial unique index in addition to the pre-check).
 */
const messageSchema = new mongoose.Schema(
  {
    conversationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Conversation",
      required: true,
    },
    senderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    receiverId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    content: {
      type: String,
      required: [true, "Message content is required"],
      trim: true,
      maxlength: [MAX_MESSAGE_LENGTH, "Message is too long"],
    },
    messageType: {
      type: String,
      enum: ["text"],
      default: "text",
    },
    clientMessageId: {
      type: String,
      trim: true,
      maxlength: 64,
    },
    isRead: {
      type: Boolean,
      default: false,
    },
    readAt: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true }
);

// Message history paging: one conversation, newest first.
messageSchema.index({ conversationId: 1, _id: -1 });
// Unread badge / unread marking for the receiving user.
messageSchema.index({ receiverId: 1, isRead: 1 });
// Idempotency: the same client message id can only be stored once per sender.
messageSchema.index(
  { senderId: 1, clientMessageId: 1 },
  {
    unique: true,
    partialFilterExpression: { clientMessageId: { $type: "string" } },
  }
);

const Message = mongoose.model("Message", messageSchema);

Message.MAX_MESSAGE_LENGTH = MAX_MESSAGE_LENGTH;

module.exports = Message;
